### ISSUE TITLE
Wrong Username or Password with good credentials

### ISSUE THREAD

**Issue by t-prod** [ptejada/uFlex#17]
Hello,

I've installed your class throught Composer.
My user has been created without problem via register().
But I cannot login with the good username and password (in clear).

It's the good login and password and I print the post values and it's the same.
How can I debug that ?

Error : Wrong username or password

<pre>$user = new Login();
$user->logout();
$user->login($_POST['username'],$_POST['password'],false);
if($user->isSigned()){
        echo "User Successfully Logged in";
    }else{
        foreach($user->log->getErrors() as $err){
          echo "<b>Error:</b> {$err} <br/ >";
      }
    }</pre>

Thanks

**Comment by gh-darvishani** [comment]
i used this code and result :
`User Registered
User Login not valid
Array
(
    [Username] => user15
    [Password] => e97a3ddde1ba04c7a6dec154122f8db778abe53b
    [Email] => user15@live.com
    [RegDate] => 1497004609
    [ID] => 18
)
`
