### ISSUE TITLE
Provide demo app

### ISSUE THREAD

**Issue by 3zzy** [ptejada/uFlex#27]
Hi,

Can you please also provide the demo app so we could see it all working together.

Thanks

**Comment by ptejada** [comment]
Hey,
Which app are you referring to?

**Comment by 3zzy** [comment]
The demo that runs on your website, it would be great if you provided as a zip so newbies like me could use it directly. Some of the things in the documentation are not clear, so a demo always helps.

Thanks

**Comment by ptejada** [comment]
The source for the demo is included in the repo

https://github.com/ptejada/uFlex/tree/master/demo

Let me know if that is what you were refering to.
