### ISSUE TITLE
Session holds onto old schema/contents after Users database schema changed

### ISSUE THREAD

**Issue by ajmedway** [ptejada/uFlex#29]
Would be good to change the UserBase class to get a fresh copy of Users row on each instatiation

**Comment by ptejada** [comment]
Hi,
User information is stored in the session for performance reason. This prevents the overhead of fetching the user from the database on every request.

If you really want to load user from the database EVERY single time try the following:
```php
$user = new ptejada\uFlex\User();

$user->start(false);
$user->session->update = true;
$user->login();
```

Let me know if it work.

**Comment by ajmedway** [comment]
This is no good, the update on the collection object invokes an array_merge() with the existing data, so if for instance I rename a custom database field name, it keeps the old fieldname and value and adds the new field name as an extra element to the User data array:

    public function update(array $updates)
    {
        $this->_data = array_merge($this->_data, $updates);
    }

Core code changes are required to set a new array from database to replace the old instead of a merge... as it stands I need all of the users to logout and log in again to cleanly handle any updates to the Users table schema.

**Comment by ptejada** [comment]
Thanks for the PR, I will add additional unittest for the session later on.
