### ISSUE TITLE
newPassword(), update() broken validation - $ Bounty

### ISSUE THREAD

**Issue by cwilliams5** [ptejada/uFlex#31]
I was trying to update uFlex to password_hash and password_verify and thought I seriously broke things. I set up a new domain with a clean uflex demo install and verified the issue is in the base code.

The change password functions, as seen on /update/password:
- will give "password changed" regardless of actual success
- validation rules are enforced only silently
- if validation rules are not met, password is not changed, but "password changed" success message and redirect occurs
- user believes password is changed, has no way of knowing
- unsure of this one, maybe its because the above is broken or maybe its a security thing, but when changing password with a hash it will act like there is a success with any hash, even invalid or expired. no feedback for user.

I haven't been able to figure out the solution myself yet.

Since this is a soon to be live project, I am placing a bounty of $75 via paypal to whomever fixes this. This is roughly 1/3 my income for this project, so I consider it fair for how much time uFlex saved me.

Thanks in advance.

**Comment by ajmedway** [comment]
I have investigated this with the latest version works fine, your implementation may be flawed... try this code here, you will find that it demands 40 chars hash and if it's not a valid hash it will give you error:

> Password could not be changed. The request cannot be validated.

in the $errors array.

    public function resetPassword($hash) {
        if (empty($hash) || strlen($hash) != 40) {
            $errors[] = '<strong>Invalid password reset token!</strong> Please ensure you copied the password reset link from your email correctly.';
        } elseif (!empty($_POST['submitted']) && $hash) {
            // Change Password with confirmation hash
            $reset_success = $uflex->newPassword(
                $hash, array(
                'Password' => $_POST['password'],
                'Password2' => $_POST['passwordConfirm'],
                )
            );
            if ($reset_success) {
                // Everything went OK, redirect to confirmation on login page with notification
            } else {
                // Add error to notification stack
                foreach ($uflex->log->getErrors() as $error_message) {
                    $errors[] = $error_message;
                }
            }
        }
    }

Please let me know if this fixes your issue?

Thanks, Alec

**Comment by cwilliams5** [comment]
Thanks for the response Alec. I feel maybe I wasn't specific enough. The problem isn't just my implementation, its the default uFlex demo implementation. If you look at the demo on the uFlex website....its not working. But here, here is a vanilla demo cloned right out of Github:

http://codywilliams.com/test/demo/

Now in the default uFlex there are only 2 validations for password: it has to be 3 characters, and Password1 and Password2 must match. On this demo, go to register account and try using a 2 character password or not matching passwords. You will see the form doesn't submit, and the appropriate fields are marked with error messages. Next, register your account properly, log in, and then go to change password. On this form, try having a 2 character password or non matching passwords. You will see the form submits, the password changes success message occurs, and the page redirects. This is the problem.

So there's the specific problem: In the uFlex demo implementation, the change password form is not working properly. The validation rules are being respected (password is not actually changed unless met), but they are not stopping the submit process and marking the form with the appropriate errors.

Now I could hack ps/change_password.php to implement my validation rules there, but that doesn't fix the bug. The bug still exists: the password validation rules declared in UserBase.php are not presenting errors on the change password page. Why should the developer need to duplicate those validation rules in another place, such as the change_password.php or password functions themselves? That can't be the intended behavior.

So a proper fix here would address this base issue in the existing Uflex base code, wherever it lie, be it in User.php, change_pasword.php, etc. Something that could be submitted as a pull request to uFlex to fix the problem for everyone.

Thanks again for your time and let me know if I can provide further information.

**Comment by ptejada** [comment]
Hey Cody,

I will look into this issue tonight. According to your findings the issue
might be the update() method. I will post back my findings.

On Mon, Feb 1, 2016, 6:18 PM Cody Williams <notifications@github.com> wrote:

> Thanks for the response Alec. I feel maybe I wasn't specific enough. The
> problem isn't just my implementation, its the default uFlex demo
> implementation. If you look at the demo on the uFlex website....its not
> working. But here, here is a vanilla demo cloned right out of Github:
>
> http://codywilliams.com/test/demo/
>
> Now in the default uFlex there are only 2 validations for password: it has
> to be 3 characters, and Password1 and Password2 must match. On this demo,
> go to register account and try using a 2 character password or not matching
> passwords. You will see the form doesn't submit, and the appropriate fields
> are marked with error messages. Next, register your account properly, log
> in, and then go to change password. On this form, try having a 2 character
> password or non matching passwords. You will see the form submits, the
> password changes success message occurs, and the page redirects. This is
> the problem.
>
> So there's the specific problem: In the uFlex demo implementation, the
> change password form is not working properly. The validation rules are
> being respected (password is not actually changed unless met), but they are
> not stopping the submit process and marking the form with the appropriate
> errors.
>
> Now I could hack ps/change_password.php to implement my validation rules
> there, but that doesn't fix the bug. The bug still exists: the password
> validation rules declared in UserBase.php are not presenting errors on the
> change password page. Why should the developer need to duplicate those
> validation rules in another place, such as the change_password.php or
> password functions themselves? That can't be the intended behavior.
>
> So a proper fix here would address this base issue in the existing Uflex
> base code, wherever it lie, be it in User.php, change_pasword.php, etc.
> Something that could be submitted as a pull request to uFlex to fix the
> problem for everyone.
>
> Thanks again for your time and let me know if I can provide further
> information.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ptejada/uFlex/issues/31#issuecomment-178249904>.
>
-- 

Sincerely,

Pablo Tejada

From Mobile

**Comment by ptejada** [comment]
Hey Cody,

I was able replicate the problem you described and issue is not in the code base. The errors are been sent back to browser but they are not been handled correctly.
![image](https://cloud.githubusercontent.com/assets/253405/12738206/bd088d2a-c92c-11e5-82f2-fff766d1b048.png)

With that been said I won't categorized this as a bug. I have mentioned it before to other developers, the demo provided should not be used as script to create websites or applications. Its purpose is to only showcase how the class can be implemented.

The fix itself is trivial, will push an update in a few minutes to close this ticket. Let me know if you have any additional questions or concerns.

**Comment by cwilliams5** [comment]
Thanks Pablo for checking it out. I didn't even think to check the JS, I was combing the PHP for an issue. I should have checked out the JSON response, that would have illuminated it for me much more. No surprise it was in the JS that is my weakest part of web development.

Thank you very much for the fix! I've read you mention before that the demo should not be depended on, but I doubt I'm the only one building on it. I consider it a great base, especially for someone like me just beginning to learn OOP. I've built on top of it of course, email functions, many security improvements, etc, but it was a very useful starting point for sure!
