### ISSUE TITLE
Version 2.0.0 development 

### ISSUE THREAD

**Issue by ptejada** [ptejada/uFlex#40]
Features to implement:
- [x] Automatically expires the session after a period of time without been accessed.
- [x] Add support for PHP 5.5 `password_*` functions.
- [x] Add backward compatibility to PHP 5.3 and 5.4 for `password_*` functions.
- [ ] Update the default password complexity. 
- [ ] Review the included demo for security improvements.
- [x] Refactor the built-in errors and handlers.
- [ ] Decouple the bundle demo into its own project

Original request #38

**Comment by aolko** [comment]
no updates...is it dead?

**Comment by ptejada** [comment]
Hey,

Is still a work in progress. I have not been updating this ticket. Although
is not yet ready, you can see the updates made so far in the 2.0
development branch.

On Fri, Apr 22, 2016, 3:21 AM aolko <notifications@github.com> wrote:

> no updates...is it dead?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ptejada/uFlex/issues/40#issuecomment-213300138>
>
-- 

Sincerely,

Pablo Tejada

From Mobile
