### ISSUE TITLE
Problem with js under Chrome

### ISSUE THREAD

**Issue by rukverc** [ptejada/uFlex#43]
windows 8.1,  chrome ver 48.0.2564.116 m
Chrome dev console said:

`Uncaught TypeError: button.button is not a function(anonymous function) 

@ main.js:6jQuery.event.dispatch 

@ jquery.js:4732elemData.handle

@ jquery.js:4544`

The browser said (url: public/ps/login.php):

`{"error":[],"confirm":"You are now login as madaras<\/b>","form":[]}`

Its generated in chrome only at login, password change and password reset.

Firefox and IE has no error at all.

**Comment by ptejada** [comment]
Hey,

Unfortunately im not able not reproduce the JS error mentioned. Im currently running Windows 10 and the same version of chrome. I will leave this ticket open in case someone else encounters the same issue.

Do note that for the next major release the demo will get the decoupled into its own project separate project.
