### ISSUE TITLE
Password verification before change

### ISSUE THREAD

**Issue by rajeshdk** [ptejada/uFlex#44]
Hi,
Please add support for three password fields Current password,New and Confirm
Thanks

**Comment by ptejada** [comment]
Hey,
This is a good idea, it is currently possible to do this type of check but there is no straight way to accomplished this.

For example to verify the password of the logged in user:

```
$hash = new \ptejada\uFlex\Hash();
if($user->Password === $hash->generateUserPassword($user, $plainTextPassword)) {
     // Current password match
}
```

**Comment by rajeshdk** [comment]
Can you please write full code for this function, I tried many times but unable to understand your codes 

```
 function changepassword () {
 include("../includes/config.php");	
	 //Proccess Password change
	 if(count($_POST)){
		$hash = @$_POST['c'];
		unset($_POST['c']);
		
		if(!$user->signed and $hash){
			//Change password with confirmation hash
			$user->new_pass($hash,$_POST);
			$redirectPage = "index.php?rdp=login";
		}else{
			//Change the password of signed in user without a confirmation hash 
			$user->update($_POST);
			$redirectPage = "index.php?rdp=home";
		}

		echo json_encode(array(
			'error'    => $user->error(),
			'confirm'  => "Password Changed",
			'form'     => $user->form_error(),
		));
	}}
```

Thanks again for you great and time saving work

**Comment by ptejada** [comment]
Hey,
Your code looks outdated which version are you using?
I recommend updating to at least  > 1.0

**Comment by rajeshdk** [comment]
Hi :+1:  Thanks for code update suggestion

Now please

`             //Process Password change
               if (count($_POST)) {
    /*
    * Covert POST into a Collection object
    * for better handling
    */
    $input = new \ptejada\uFlex\Collection($_POST);

    $hash = $input->c;

    if (!$user->isSigned() and $hash) {
        //Change Password with confirmation hash
        $user->newPassword(
            $hash,
            array(
                'Password'  => $input->Password,
                'Password2' => $input->Password2,
            )
        );
        $redirectPage = "login";
    } else {
        //Change the Password of signed in user without a confirmation hash
        $user->update(
            array(
                'Password'  => $input->Password,
                'Password2' => $input->Password2,
            )
        );
        $redirectPage = 'account';
    }

    echo json_encode(
        array(
            'error'   => $user->log->getAllErrors(),
            'confirm' => 'Password Changed',
            'form'    => $user->log->getFormErrors(),
        )
    );
}`

Form 
<div class="form-group">
				<label>New Password:</label>
				<input name="Password" type="password" class="form-control" required>
			</div>

			<div class="form-group">
				<label>Confirm New Password:</label>
				<input name="Password2" type="password" class="form-control" required>
			</div>
			<input name="c" type="hidden" value="<?php echo getVar("c")?>">

**Comment by ptejada** [comment]
Hi,

Now you should try the block of code that i provided earlier. Let me know if it works

**Comment by rajeshdk** [comment]
Thank you Thank you Thank you :+1:  :100:
