### ISSUE TITLE
Disable Guess/Guest mode

### ISSUE THREAD

**Issue by rajeshdk** [ptejada/uFlex#45]
Hi,
is there any way to disable Guess. It happen when user try with "spacebar" or 0
Thanks

**Comment by ptejada** [comment]
Hey,
What do you mean by disabling the guest mode? a user is either signed in or is not.

**Comment by rajeshdk** [comment]
Hi,
I mean, it is not a security problem, user automatic redirect again to login page but not feel good.. Anyway I am just asking. It is not a serious issue.
<img width="756" alt="screen shot 03-18-16 at 12 45 pm" src="https://cloud.githubusercontent.com/assets/11823896/13871058/6914a574-ed07-11e5-8f46-a658d1bf2cfe.PNG">

My last question is

Dude, I am using direct

> if(!$user->GroupID>1){die();}

instead

```
if($user->isSigned()) {
if(!$user->GroupID>1){die();}
}
```
Is direct use vulnerable ? or okay

**Comment by ptejada** [comment]
Hey,

You can use 

```
if(!$user->isSigned() || !$user->GroupID>1){die();}
```

About the screenshot, you are saying that message comes up even when a user is not signed in? If so, you should be able to control that in your application logic. Are you checking if user has successfully Signed in before displaying that message.

**Comment by rajeshdk** [comment]
Okay Thanks
