### ISSUE TITLE
PDO general error on login() (LogLogin)

### ISSUE THREAD

**Issue by abuisine** [ptejada/uFlex#46]
I am able to reproduce (not very easily) a general error when my user login a couple of times in a row (because of page reloading).

Basically it appears that a fetchAll is called on an UPDATE query (which is not supposed to happen).

**Flow :**
login() calls LogLogin() which calls runQuery() with `$arguments` not being `false`
the request is quite simple: `UPDATE _table_  SET LastLogin=:stamp WHERE ID=:id`

**Line 193 in DB_Table :**
```
        // If there are no arguments, execute the statement
        if (!$arguments) {
            $stmt->execute();
        }

        $rows = $stmt->rowCount();
        $rows = ($rows > 0) ? $rows : count($stmt->fetchAll());
```

**Trace :**
```
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error' in /var/www/default/tools/vendor/ptejada/uflex/src/DB_Table.php:202
Stack trace:
#0 /var/www/default/tools/vendor/ptejada/uflex/src/DB_Table.php(202): PDOStatement->fetchAll()
#1 /var/www/default/tools/vendor/ptejada/uflex/src/User.php(295): ptejada\\uFlex\\DB_Table->runQuery('UPDATE _table_ ...', Array)
#2 /var/www/default/tools/vendor/ptejada/uflex/src/User.php(96): ptejada\\uFlex\\User->logLogin()
#3 /var/www/default/lib/classUFlex.php(15): ptejada\\uFlex\\User->login('', '', false)
#4 /var/www/default/tools/vendor/ptejada/uflex/src/User.php(279): classUFlex->login()
#5 /var/www/default/modules/header/header.php(7): ptejada\\uFlex\\User->start(true)
#6 /var/www/default/lib/classExecuter.php(78): header->__construct(Object(Executer), Object(Smarty))
#7 /var/www/default/lib/classExecuter.php(36): Executer->loadModules()
#8 /var/www/default/lib/classCore.php(443): Executer->__construct(Object(Smarty), Object(classLanguages), Object(PDO),  in /var/www/default/tools/vendor/ptejada/uflex/src/DB_Table.php on line 202
```

**Comment by abuisine** [comment]
Ok got it, when the LastLogin is set two times within the same second, the update returns that 0 rows has been updated, which triggers the fetchAll in the code.

Any idea here ? :)

**Comment by ptejada** [comment]
Hey,
Thank you for the research, will look further into this and come up with a solution. I might not be able to reproduce the issue but should be able to patch `fetchAll()` been call on a update statement.
